# Generated by Django 4.2.5 on 2023-09-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedidoplato_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoplato',
            name='pedido_id',
            field=models.ForeignKey(db_column='pedido_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pedidoplatos', to='api.pedido'),
        ),
    ]
